
--CASE

--Compreendendo o uso:
SELECT NOME_DO_PRODUTO, SABOR, PRECO_DE_LISTA 
FROM TABELA_DE_PRODUTOS;

SELECT NOME_DO_PRODUTO, PRECO_DE_LISTA 
FROM TABELA_DE_PRODUTOS WHERE SABOR = 'Manga';

SELECT NOME_DO_PRODUTO, PRECO_DE_LISTA, 
(CASE WHEN PRECO_DE_LISTA > 12 THEN 'PRODUTO CARO' 
      WHEN PRECO_DE_LISTA >= 7 AND PRECO_DE_LISTA < 12 THEN 'PRODUTO EM CONTA' 
      ELSE 'PRODUTO BARATO' END) AS CLASSIFICACAO 
FROM TABELA_DE_PRODUTOS 
WHERE SABOR = 'Manga';


--CASE com ORDER BY
SELECT NOME_DO_PRODUTO, PRECO_DE_LISTA,
(CASE WHEN PRECO_DE_LISTA >12 THEN 'PRODUTO CARO' 
      WHEN PRECO_DE_LISTA >= 7 AND PRECO_DE_LISTA < 12 THEN 'PRODUTO EM CONTA' 
      ELSE 'PRODUTO BARATO' END) AS CLASSIFICACAO 
FROM TABELA_DE_PRODUTOS 
WHERE SABOR = 'Manga'
ORDER BY CLASSIFICACAO;


--CASE com GROUP BY
SELECT 
(CASE WHEN PRECO_DE_LISTA >12 THEN 'PRODUTO CARO' 
      WHEN PRECO_DE_LISTA >= 7 AND PRECO_DE_LISTA < 12 THEN 'PRODUTO EM CONTA' 
      ELSE 'PRODUTO BARATO' END) AS CLASSIFICACAO, COUNT(*) AS NUMERO_DE_PRODUTOS 
FROM TABELA_DE_PRODUTOS 
GROUP BY CLASSIFICACAO; --GROUP BY NÃO RECONHECE O APELIDO. SOLUÇÃO ABAIXO:

SELECT 
(CASE WHEN PRECO_DE_LISTA >12 THEN 'PRODUTO CARO' 
      WHEN PRECO_DE_LISTA >= 7 AND PRECO_DE_LISTA < 12 THEN 'PRODUTO EM CONTA' 
      ELSE 'PRODUTO BARATO' END) AS CLASSIFICACAO, COUNT(*) AS NUMERO_DE_PRODUTOS 
FROM TABELA_DE_PRODUTOS 
GROUP BY (CASE WHEN PRECO_DE_LISTA >12 THEN 'PRODUTO CARO' 
      WHEN PRECO_DE_LISTA >= 7 AND PRECO_DE_LISTA < 12 THEN 'PRODUTO EM CONTA' 
      ELSE 'PRODUTO BARATO' END);


--EXERCÍCIO: Para cada cliente temos seus limites de crédito mensais. 
--           Liste somente o nome dos clientes e os classifique por:
--				. Acima ou igual a 150.000 - Clientes grandes
--				. Entre 150.000 e 110.000 - Clientes médios
--				. Menores que 110.000 Clientes pequenos

SELECT * FROM TABELA_DE_CLIENTES;

SELECT NOME, LIMITE_DE_CREDITO,
(CASE	WHEN LIMITE_DE_CREDITO > 150000 THEN 'Cliente Grande'
		WHEN LIMITE_DE_CREDITO BETWEEN 110000 AND 150000 THEN 'Cliente Médio'
		ELSE 'Cliente Pequeno' END) AS TIPO_CLIENTE
FROM TABELA_DE_CLIENTES;

SELECT 
(CASE	WHEN LIMITE_DE_CREDITO > 150000 THEN 'Cliente Grande'
		WHEN LIMITE_DE_CREDITO BETWEEN 110000 AND 150000 THEN 'Cliente Médio'
		ELSE 'Cliente Pequeno' END) AS TIPO_CLIENTE, COUNT(*) AS QUANTIDADE
FROM TABELA_DE_CLIENTES
GROUP BY (CASE	WHEN LIMITE_DE_CREDITO > 150000 THEN 'Cliente Grande'
		WHEN LIMITE_DE_CREDITO BETWEEN 110000 AND 150000 THEN 'Cliente Médio'
		ELSE 'Cliente Pequeno' END);