
--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
-- Filtro: WHERE


SELECT * FROM TABELA_DE_PRODUTOS;

SELECT * FROM TABELA_DE_PRODUTOS WHERE 1=1;

SELECT * FROM TABELA_DE_PRODUTOS WHERE 1=0;

SELECT * FROM TABELA_DE_PRODUTOS WHERE CODIGO_DO_PRODUTO = 290478;

SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR = 'Laranja';

SELECT * FROM TABELA_DE_PRODUTOS WHERE EMBALAGEM = 'PET';

SELECT * FROM TABELA_DE_PRODUTOS WHERE EMBALAGEM = 'pet';



-- Filtrando dados Quantitativos

SELECT * FROM TABELA_DE_CLIENTES WHERE BAIRRO >= 'Lapa'; --ORDEM ALFABÉTICA

SELECT * FROM TABELA_DE_CLIENTES WHERE IDADE < 18;

SELECT * FROM TABELA_DE_CLIENTES WHERE IDADE <= 18;

SELECT * FROM TABELA_DE_CLIENTES WHERE IDADE <> 18;

SELECT * FROM TABELA_DE_CLIENTES WHERE DATA_DE_NASCIMENTO >= '1995-11-14'; 

SELECT * FROM TABELA_DE_CLIENTES WHERE DATA_DE_NASCIMENTO <= '1995-11-14';
