
-- AND, OR, IN, BETWEEN, NOT

SELECT * FROM [TABELA_DE_PRODUTOS];

-- AND e OR
SELECT * FROM [TABELA_DE_PRODUTOS] WHERE SABOR = 'Manga' AND TAMANHO = '470 ml'; --AMBOS TÊM QUE SE ATENDIDOS
SELECT * FROM [TABELA_DE_PRODUTOS] WHERE SABOR = 'Manga' OR TAMANHO = '470 ml'; 


--IN substituíndo o OR
SELECT * FROM [TABELA_DE_PRODUTOS] WHERE SABOR in ( 'Manga','Melancia','Cereja'); -- SUBSTITUI VÁRIOS OR
SELECT * FROM [TABELA_DE_PRODUTOS] WHERE SABOR = 'Manga' OR SABOR = 'Melancia' OR SABOR = 'Cereja'; 


--BETWEEN substituíndo o AND
SELECT * FROM TABELA_DE_CLIENTES WHERE 
CIDADE in ('Rio de Janeiro', 'Sao Paulo') AND (IDADE >= 20 AND IDADE <= 25);
SELECT * FROM TABELA_DE_CLIENTES WHERE 
CIDADE in ('Rio de Janeiro', 'Sao Paulo') AND (IDADE BETWEEN 20 AND 25);


--NOT e suas possibilidades
SELECT * FROM [TABELA_DE_PRODUTOS] WHERE NOT (SABOR = 'Manga' AND TAMANHO = '470 ml');
SELECT * FROM [TABELA_DE_PRODUTOS] WHERE NOT (SABOR = 'Manga' OR TAMANHO = '470 ml');
SELECT * FROM [TABELA_DE_PRODUTOS] WHERE NOT SABOR = 'Manga' AND TAMANHO = '470 ml'; --O NOT SÓ FUNCIONA NO 1°


--COMBINAÇÕES VARIADAS
SELECT * FROM TABELA_DE_PRODUTOS WHERE 
SABOR in ('Manga', 'Laranja', 'Melancia') AND TAMANHO = '1 Litro';
SELECT * FROM TABELA_DE_CLIENTES WHERE 
CIDADE in ('Rio de Janeiro', 'Sao Paulo');
SELECT * FROM TABELA_DE_CLIENTES WHERE 
CIDADE in ('Rio de Janeiro', 'Sao Paulo') AND IDADE >= 20;