
--TOP apresenta uma amostra da tabela

SELECT TOP 5 * FROM TABELA_DE_PRODUTOS;

SELECT TOP 5 * FROM TABELA_DE_PRODUTOS WHERE SABOR = 'Maca';


--Exercício:

SELECT TOP 10 * FROM NOTAS_FISCAIS WHERE DATA_VENDA = '01/10/2017';