
--ORDER BY ____ ASC_dente ou DESC_dente

--Entendendo as formas de ordem
SELECT * FROM TABELA_DE_PRODUTOS ORDER BY PRECO_DE_LISTA;
SELECT * FROM TABELA_DE_PRODUTOS ORDER BY PRECO_DE_LISTA ASC;
SELECT * FROM TABELA_DE_PRODUTOS ORDER BY PRECO_DE_LISTA DESC;

--Ordenando mais de uma lista na Query
SELECT * FROM TABELA_DE_PRODUTOS ORDER BY NOME_DO_PRODUTO;
SELECT * FROM TABELA_DE_PRODUTOS ORDER BY EMBALAGEM, NOME_DO_PRODUTO;
SELECT * FROM TABELA_DE_PRODUTOS ORDER BY EMBALAGEM DESC, NOME_DO_PRODUTO DESC;

--Combinações com ORDER BY e TOP
SELECT TOP 5 * FROM TABELA_DE_PRODUTOS ORDER BY PRECO_DE_LISTA DESC;


--Exercício: Qual foi a maior venda do produto "Linha Refrescante - 1 Litro - Morango/Limao" em quantidade?

SELECT * FROM TABELA_DE_PRODUTOS WHERE NOME_DO_PRODUTO = 'Linha Refrescante - 1 Litro - Morango/Limao';
SELECT TOP 1 * FROM ITENS_NOTAS_FISCAIS WHERE CODIGO_DO_PRODUTO = '1101035' ORDER BY QUANTIDADE DESC;

