
--GROUP BY  

-- Faz: soma SUM(), média AVG(), contagem COUNT(), máximo MAX(), mínimo MIN()
-- Para usar as funções acima temos que usar o GROUP BY.

--Agrupamento
SELECT CIDADE, IDADE FROM TABELA_DE_CLIENTES ORDER BY CIDADE, IDADE; --ORDENA
SELECT CIDADE, IDADE FROM TABELA_DE_CLIENTES GROUP BY CIDADE, IDADE; --AGRUPA

--SUM()
SELECT CIDADE, SUM(IDADE) AS [SOMA DA IDADE] 
FROM TABELA_DE_CLIENTES GROUP BY CIDADE;
SELECT CIDADE, SUM(IDADE) AS [SOMA DA IDADE], SUM(LIMITE_DE_CREDITO) AS [SOMA DO CREDITO]
FROM TABELA_DE_CLIENTES GROUP BY CIDADE;
SELECT CIDADE, SUM(IDADE) AS [SOMA DA IDADE], SUM(LIMITE_DE_CREDITO) AS [SOMA DO CREDITO] 
FROM TABELA_DE_CLIENTES GROUP BY CIDADE;

--AVG()
SELECT CIDADE, AVG(IDADE) AS IDADE, AVG(LIMITE_DE_CREDITO) FROM TABELA_DE_CLIENTES GROUP BY CIDADE;

--COUNT(*) conta as linhas
SELECT CIDADE, COUNT(*) AS NUMERO_DE_CLIENTES FROM TABELA_DE_CLIENTES GROUP BY CIDADE;
SELECT EMBALAGEM, COUNT(*) AS NUMERO_DE_CLIENTES FROM TABELA_DE_PRODUTOS;
SELECT EMBALAGEM, COUNT(*) AS NUMERO_DE_CLIENTES FROM TABELA_DE_PRODUTOS WHERE SABOR = 'Laranja' GROUP BY EMBALAGEM;

--MAX
SELECT CIDADE, MAX(IDADE) AS [CLIENTE MAIS VELHO] FROM TABELA_DE_CLIENTES GROUP BY CIDADE;

--MIN
SELECT CIDADE, MIN(IDADE) AS [CLIENTE MAIS VELHO] FROM TABELA_DE_CLIENTES GROUP BY CIDADE;


--EXERCÍCIO: Quantas vendas foram feitas com quantidade igual a 99 litros para o produto '1101035'?
SELECT COUNT(*) FROM ITENS_NOTAS_FISCAIS WHERE CODIGO_DO_PRODUTO = '1101035' AND QUANTIDADE = 99; --79 vendas