
--HAVING 
--substitui o WHERE em algumas consultas


--Funcionamento do HAVING
SELECT ESTADO, SUM(LIMITE_DE_CREDITO) AS CREDITO FROM TABELA_DE_CLIENTES GROUP BY ESTADO;

SELECT ESTADO, SUM(LIMITE_DE_CREDITO) AS CREDITO FROM TABELA_DE_CLIENTES 
WHERE SUM(LIMITE_DE_CREDITO) >= 900000 GROUP BY ESTADO; --O WHERE NÃO FUNCIONA COM ESSE TIPO DE EXPRESSÃO

SELECT ESTADO, SUM(LIMITE_DE_CREDITO) AS CREDITO FROM TABELA_DE_CLIENTES 
GROUP BY ESTADO HAVING SUM(LIMITE_DE_CREDITO) >= 900000; --NO LUGAR DO WHERE USAMOS O HAVING


--Outro exemplo
SELECT EMBALAGEM, MAX(PRECO_DE_LISTA) AS PRECO_MAX, MIN(PRECO_DE_LISTA) AS PRECO_MIN 
FROM TABELA_DE_PRODUTOS GROUP BY EMBALAGEM;

SELECT EMBALAGEM, MAX(PRECO_DE_LISTA) AS PRECO_MAX, MIN(PRECO_DE_LISTA) AS PRECO_MIN 
FROM TABELA_DE_PRODUTOS WHERE PRECO_DE_LISTA >= 10 GROUP BY EMBALAGEM;

SELECT EMBALAGEM, MAX(PRECO_DE_LISTA) AS PRECO_MAX, MIN(PRECO_DE_LISTA) AS PRECO_MIN 
FROM TABELA_DE_PRODUTOS WHERE PRECO_DE_LISTA >= 10 GROUP BY EMBALAGEM 
HAVING MAX(PRECO_DE_LISTA) >=20;



--EXERCÍCIO: Verifique as quantidades totais de vendas de cada produto e ordene do maior para o menor.
--           E liste somente os produtos que venderam mais que 394000 unidades.

SELECT * FROM TABELA_DE_PRODUTOS; -- 31 PRODUTOS
SELECT * FROM ITENS_NOTAS_FISCAIS;

SELECT CODIGO_DO_PRODUTO, SUM(QUANTIDADE) AS QUANTIDADE 
FROM ITENS_NOTAS_FISCAIS 
GROUP BY CODIGO_DO_PRODUTO
HAVING SUM(QUANTIDADE) >= 394000
ORDER BY QUANTIDADE DESC;

--Quero descobrir como usar dados de uma tabela diferente nessa - Resposta: JOIN

SELECT TABELA_DE_PRODUTOS.NOME_DO_PRODUTO, SUM(QUANTIDADE) AS QUANTIDADE 
FROM ITENS_NOTAS_FISCAIS INNER JOIN TABELA_DE_PRODUTOS 
ON TABELA_DE_PRODUTOS.CODIGO_DO_PRODUTO = ITENS_NOTAS_FISCAIS.CODIGO_DO_PRODUTO
GROUP BY TABELA_DE_PRODUTOS.NOME_DO_PRODUTO
HAVING SUM(QUANTIDADE) >= 394000
ORDER BY QUANTIDADE DESC;