
--INNER JOIN: conectando tabelas

SELECT * FROM TABELA_DE_VENDEDORES;

SELECT * FROM NOTAS_FISCAIS;

SELECT MATRICULA, COUNT(*) AS NUMERO_VENDAS FROM NOTAS_FISCAIS GROUP BY MATRICULA;

--COMO USAR O INNER JOIN
SELECT MATRICULA, NOME, COUNT(*) AS NUMERO_VENDAS FROM NOTAS_FISCAIS 
INNER JOIN TABELA_DE_VENDEDORES 
ON NOTAS_FISCAIS.MATRICULA = TABELA_DE_VENDEDORES.MATRICULA 
GROUP BY MATRICULA, NOME; --DEVE-SE DECLARAR DE ONDE ESSAS TABELAS VÊM NO SELECT, COMO FEITO ABAIXO

--sem apelido de tabela
SELECT NOTAS_FISCAIS.MATRICULA, TABELA_DE_VENDEDORES.NOME, COUNT(*) AS NUMERO_VENDAS 
FROM NOTAS_FISCAIS 
INNER JOIN TABELA_DE_VENDEDORES 
ON NOTAS_FISCAIS.MATRICULA = TABELA_DE_VENDEDORES.MATRICULA 
GROUP BY NOTAS_FISCAIS.MATRICULA, TABELA_DE_VENDEDORES.NOME;

--com apelido de tabela
SELECT NF.MATRICULA, TV.NOME, COUNT(*) AS NUMERO_VENDAS 
FROM NOTAS_FISCAIS NF 
INNER JOIN TABELA_DE_VENDEDORES TV 
ON NF.MATRICULA = TV.MATRICULA 
GROUP BY NF.MATRICULA, TV.NOME;

--BOA PRÁTICA: colocar a tabela superior antes da inferior ou seja 1 para n
SELECT NF.MATRICULA, TV.NOME, COUNT(*) AS NUMERO_NOTAS 
FROM TABELA_DE_VENDEDORES TV  
INNER JOIN NOTAS_FISCAIS NF
ON NF.MATRICULA = TV.MATRICULA 
GROUP BY NF.MATRICULA, TV.NOME;


--EXERCÍCIO:
--Verifique as quantidades totais de vendas de cada produto e ordene do maior para o menor.
--E liste somente os produtos que venderam mais que 394000 unidades.
--Dê o nome do produto junto ao seu código

SELECT INF.CODIGO_DO_PRODUTO, TP.NOME_DO_PRODUTO, SUM(INF.QUANTIDADE) AS QUANTIDADE
FROM TABELA_DE_PRODUTOS TP
INNER JOIN ITENS_NOTAS_FISCAIS INF
ON TP.CODIGO_DO_PRODUTO = INF.CODIGO_DO_PRODUTO
GROUP BY INF.CODIGO_DO_PRODUTO, TP.NOME_DO_PRODUTO
HAVING SUM(QUANTIDADE) >= 394000
ORDER BY QUANTIDADE DESC;


